### PR TITLE
small changes for current flixel compatibility

### PR DESCRIPTION
**Pull request by ninjamuffin99**
adds a few small changes to make the game compatible with the latest versionf of lime, openfl, and flixel!

### CODE REVIEW

**Comment by richvreeland** [comment]
hey that's awesome ! thanks ! i'll take a look ASAP

**Comment by ninjamuffin99** [comment]
woohoo nice :) 
was there anywhere to play this online or download it other than github? When the haxeflixel version came out I feel like I was able to play it online or download it, but since then I've tried coming back to it and I've always had to recompile it for myself since I couldn't find any download or browser links!

**Comment by richvreeland** [comment]
@ninjamuffin99 there are old builds here : [link](http://disasterpeace.com/blog/january)

But I think what I'll do is add releases to git, and link to it from a more prominent part of my website so people have a better time finding it. maybe i'll make a video/announcement to : )

**Comment by ninjamuffin99** [comment]
yeah that sounds good, I've been around the block with haxeflixel + github actions, back earlier this year in January (hah!) I put together an updated/haxeflixel version of Canabalt by Finji, and when I did that I also got a nice clean little Github Actions config cooked nicely to compile for Windows, Mac, Linux, and HTML5

https://github.com/ninjamuffin99/canabalt-hf/blob/main/.github/workflows/build.yml

Note, on canabalt-hf i used [`hmm`](https://github.com/andywhite37/hmm) to handle haxelib versioning (which I do personally recommend and makes me happy)

**Comment by richvreeland** [comment]
@ninjamuffin99 hey that's really cool ! i don't really know anything about that stuff - if you're up for it, maybe you could help me set it up ? i'd love to automate cross-platform builds in case there are any tweaks to do (i have a few in mind :)

**Pull request merged**
